import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const inter = Lato({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata: Metadata = {
   title: "Next Landing Page",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={`${inter.className} min-h-dvh bg-primary relative`}>
            <Header />
            {children}
         </body>
      </html>
   );
}
